[project]
name = "misalignment-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "inspect-ai>=0.3.122",
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.7",
    "openai>=1.99.9",
    "together>=1.5.25",
]
